vog/config/routes.rb
Vog::Application.routes.draw do

  resources :groups do 
    resources :members do
      resources :users
    end
  end

=begin  
  resources :users do
    resources :members do
      resources :groups 
    end
  end
=end

  resources :groups do 
    resources :slams, :name_prefix => "group_"
  end

  resources :users do 
    resources :slams
  end
  
  resources :slams do 
    resources :rounds, :name_prefix => "slam_"
  end
  
  resources :slams do 
    resources :participants
  end
  
  resources :rounds do
    resources :scores
  end

resources :scores 
resources :poets

root :to => "users#index"

end

vog/app/models/participant.rb
class Participant < ActiveRecord::Base
  attr_accessible :poet, :slam, :letterOrder
  belongs_to :poet
  belongs_to :slam
  belongs_to :round
  has_many :scores 
  has_many :rounds, :through => :scores
end

vog/app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @participants }
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
    @participant = Participant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/new
  # GET /participants/new.json
  def new
    @participant = Participant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/1/edit
  def edit
    @participant = Participant.find(params[:id])
  end

  # POST /participants
  # POST /participants.json
  def create
    @slam = Slam.find(params[:slam_id])
    @participant = @slam.participants.create(params[:participant])
	
    respond_to do |format|
      if @participant.save
        format.html { redirect_to @slam, notice: 'Participant was successfully created.' }
        format.json { render json: @participant, status: :created, location: @participant }
      else
        format.html { render action: "new" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /participants/1
  # PUT /participants/1.json
  def update
    @participant = Participant.find(params[:id])

    respond_to do |format|
      if @participant.update_attributes(params[:participant])
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :no_content }
    end
  end
end

vog/app/helpers/participants_helper.rb
module ParticipantsHelper
end

vog/app/views/participants/_form.html.erb
<%= form_for ([@slam, @slam.participants.build]) do |f| %>

<% if @slam.errors.any? %>
   <div id="error_explanation">
      <h2><%= pluralize(@slam.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @slam.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	
<div class="field">
    <%= f.label :letterOrder, "Order" %><br />
    <%= f.text_field :letterOrder %>
</div>
 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vog/app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

vog/app/views/participants/index.html.erb
<h1>Participants</h1>

<table>
  <tr>
    <th></th>
    <th></th>
  </tr>

<% @slam.participants.each do |participant| %>
  <tr>
    <td><%= link_to participant.poet.poetName, participant %></td>
    <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure? Any scores connected to this Participant will be delted.' } %></td>
  </tr>
<% end %>
</table>

<br />

vog/app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

vog/app/views/participants/roundsIndex.html.erb
<table>
  <tr>
    <th>Participant</th>
    <th>Score</th>
  </tr>

<% @round.slam.participants.each do |participant| %>
  <tr>
    <td><%=  participant.poet.poetName %></td>
    <td>
      <% if Score.where("participant_id = ? and round_id = ?", participant.id, @round.id).exists? %>
	<%= (Score.where("participant_id = ? and round_id = ?", participant.id, @round.id)).first.finalScore %>
      <% else %>
	<%= link_to 'Add Scores!', new_score_path(:round => @round, :participant => participant.id) %>
       <% end %> 
    </td>
  </tr>
<% end %>
</table>

<br />

vog/app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>