vog/config/routes.rb
Vog::Application.routes.draw do

  resources :groups do 
    resources :members do
      resources :users
    end
  end

=begin  
  resources :users do
    resources :members do
      resources :groups 
    end
  end
=end

  resources :groups do 
    resources :slams, :name_prefix => "group_"
  end

  resources :users do 
    resources :slams
  end
  
  resources :slams do 
    resources :rounds, :name_prefix => "slam_"
  end
  
  resources :slams do 
    resources :participants
  end
  
  resources :rounds do
    resources :scores
  end

resources :scores 
resources :poets

root :to => "users#index"

end

vog/app/models/slam.rb
class Slam < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name, :user, :location, :timeLimit, :date, :hostFirstName, :hostLastName, :numWinners, :numParticipants
  has_many :rounds, :dependent => :delete_all
  has_many :participants, :dependent => :delete_all
  after_create :create_first_round 

  validates :name, :presence => true, :length => {:minimum => 3}, :uniqueness => {:case_senstitive => false}
  validates :numParticipants, :presence => true
  validates :timeLimit, :numericality => true

  #automatically creates 4 rounds for the slam
  def create_first_round
   for i in 1..4	
    Round.create(:slam_id => self.id, :roundNumber => i)
   end
  end 

end

vog/app/controllers/slams_controller.rb
class SlamsController < ApplicationController
  # GET /slams
  # GET /slams.json
  def index
    @slams = Slam.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @slams }
    end
  end

  # GET /slams/1
  # GET /slams/1.json
  def show
    @slam = Slam.find(params[:id])
    @slamFull = @slam.participants.count >= @slam.numParticipants 
    @poet = Poet.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @slam }
    end
  end

  # GET /slams/new
  # GET /slams/new.json
  def new
    @slam = Slam.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @slam }
    end
  end

  # GET /slams/1/edit
  def edit
    @slam = Slam.find(params[:id])
  end

  # POST /slams
  # POST /slams.json
  def create
    @user = User.find(params[:user_id])
    @slam = @user.slams.create(params[:slam])
    
    respond_to do |format|
      if @slam.save
        format.html { redirect_to slam_path(@slam), notice: 'Let the Games Begin!' }
        
	format.json { render json: @slam, status: :created, location: @slam }
      else
	format.html { redirect_to user_path(@user, {:errors2 => @user.errors })}
#	format.json { render json: @user.errors, status: :unprocessable_entity }
     end
    end 
 end

  # PUT /slams/1
  # PUT /slams/1.json
  def update
    @slam = Slam.find(params[:id])

    respond_to do |format|
      if @slam.update_attributes(params[:slam])
        format.html { redirect_to @slam, notice: 'Slam was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slams/1
  # DELETE /slams/1.json
  def destroy
    @slam = Slam.find(params[:id])
    @user = User.find(@slam.user_id)
    @slam.destroy
    redirect_to user_path(@user)
  end

  def actions
   end 
    
end

vog/app/helpers/slams_helper.rb
module SlamsHelper
end

vog/app/views/slams/_form.html.erb
 <%= form_for([@user, @user.slams.build]) do |f| %>
  
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.label :name, "Slam Name" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location, "Slam Location" %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :hostFirstName, "Host First Name"%><br />
    <%= f.text_field :hostFirstName %>
  </div>
  <div class="field">
    <%= f.label :hostLastName, "Host Last Name" %><br />
    <%= f.text_field :hostLastName %>
  </div>
  <div class="field">
    <%= f.label :timeLimit, "Time Limit"%><br />
Enter a decimal of the maximum time before deduction.<br> 
For example if 3 minute limit w/ 10 second grace period, enter 3.10<br>
    <%= f.text_field :timeLimit %>
  </div>
  <div class="field">
    <%= f.label :numParticipants, "Number of Teams"%><br />
    <%= f.select(:numParticipants, [[3, 3], [4, 4], [5,5] ]) %>
 </div>
   Note: All Team Slams Are Built With Four Rounds
  <br>
<br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vog/app/views/slams/actions.html.erb
"hello"

vog/app/views/slams/edit.html.erb
<h1>Editing slam</h1>

<%= render 'form' %>

<%= link_to 'Show', @slam %> |
<%= link_to 'Back', slams_path %>

vog/app/views/slams/index.html.erb
<h1>Listing slams</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @slams.each do |slam| %>
  <tr>
    <td><%= slam.name %></td>
    <td><%= link_to 'Show', slam %></td>
    <td><%= link_to 'Edit', edit_slam_path(slam) %></td>
    <td><%= link_to 'Destroy', slam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Slam', new_slam_path %>

vog/app/views/slams/new.html.erb
<h1>New slam</h1>

<%= render 'form' %>

<%= link_to 'Back', slams_path %>

vog/app/views/slams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @slam.user.userName %>
<p>
    <b>Slam:</b> <%= @slam.name %>
    <b>Date:</b> <%= @slam.created_at.strftime("%a %b #{@slam.created_at.day.ordinalize}") %>
    <b>Host:</b> <%= @slam.hostFirstName%> <%= @slam.hostLastName%>
    <b>Location:</b> <%= @slam.location%>

<br>
<br>
<%= render :template => "participants/index" %>
<% if !@slamFull %>
<h2> Add Teams to this Slam!</h2> 
This slam requires <%= @slam.numParticipants %> participants to begin scoring.
<br>
<br>
<%= render "poets/form",:slam => @slam %>
<br>
**change poet form so clicking create takes them back here!
<% else %>
    <%= link_to 'Round 1', slam_round_path(@slam, @slam.rounds[0]) %>
<% end %>
<br>
<p>
<%= link_to 'Edit Slam', edit_slam_path(@slam) %> |
<%= link_to 'Back', user_path(@slam.user) %>