vog/config/routes.rb
Vog::Application.routes.draw do

  resources :groups do 
    resources :members do
      resources :users
    end
  end

=begin  
  resources :users do
    resources :members do
      resources :groups 
    end
  end
=end

  resources :groups do 
    resources :slams, :name_prefix => "group_"
  end

  resources :users do 
    resources :slams
  end
  
  resources :slams do 
    resources :rounds, :name_prefix => "slam_"
  end
  
  resources :slams do 
    resources :participants
  end
  
  resources :rounds do
    resources :scores
  end

resources :scores 
resources :poets

root :to => "users#index"

end

vog/app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :slam
  has_many :scores
  has_many :participants, :through => :scores
  validates :numPoets, :allow_nil => true, :numericality => { :only_integer => true }
  validates :roundNumber, :presence => true, :numericality => { :only_integer => true }
  attr_accessible :slam_id, :roundNumber 
end

vog/app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  # GET /rounds
  # GET /rounds.json
  def index
    @rounds = Round.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rounds }
    end
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
    @round = Round.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @round }
    end
  end

  # GET /rounds/new
  # GET /rounds/new.json
  def new
    @round = Round.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @round }
    end
  end

  # GET /rounds/1/edit
  def edit
    @round = Round.find(params[:id])
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(params[:round])

    respond_to do |format|
      if @round.save
        format.html { redirect_to @round, notice: 'Round was successfully created.' }
        format.json { render json: @round, status: :created, location: @round }
      else
        format.html { render action: "new" }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rounds/1
  # PUT /rounds/1.json
  def update
    @round = Round.find(params[:id])

    respond_to do |format|
      if @round.update_attributes(params[:round])
        format.html { redirect_to @round, notice: 'Round was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @round.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round = Round.find(params[:id])
    @round.destroy

    respond_to do |format|
      format.html { redirect_to rounds_url }
      format.json { head :no_content }
    end
  end
end

vog/app/helpers/rounds_helper.rb
module RoundsHelper
end

vog/app/views/rounds/_form.html.erb
<%= form_for(@round) do |f| %>
  <% if @round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% @round.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :slam_id %><br />
    <%= f.number_field :slam_id %>
  </div>
   <div class="field">
    <%= f.label :numPoets %><br />
    <%= f.text_field :numPoets %>
  </div>
  <div class="field">
    <%= f.label :roundNumber %><br />
    <%= f.text_field :roundNumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vog/app/views/rounds/edit.html.erb
<h1>Editing round</h1>

<%= render 'form' %>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>

vog/app/views/rounds/index.html.erb
<h1>Listing rounds</h1>

<table>
  <tr>
    <th>Slam</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rounds.each do |round| %>
  <tr>
    <td><%= round.slam_id %></td>
    <td><%= link_to 'Show', round %></td>
    <td><%= link_to 'Edit', edit_round_path(round) %></td>
    <td><%= link_to 'Destroy', round, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Round', new_round_path %>

vog/app/views/rounds/new.html.erb
<h1>New round</h1>

<%= render 'form' %>

<%= link_to 'Back', rounds_path %>

vog/app/views/rounds/show.html.erb
<p id="notice"><%= notice %></p>
<i>The point is not the points, the point is the poetry. </i> 

<p>
  <b>Slam:</b>
  <%= @round.slam.name %>
</p>
<h2>Round <%= @round.roundNumber %></h2>

<%= render :template => "participants/roundsIndex" %>


<% if @round.roundNumber < 4 %>
<%= link_to 'Next Round', slam_round_path(@round.slam, @round.slam.rounds[@round.roundNumber]) %>
<% else %>
Final Round of this Slam
Maybe OneDay the App will have a Results Model 
Each Slam has one Result 
It will list the participants in order based on final score! 
<% end %>